//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC_alert_tool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alertDatabaseEntities : DbContext
    {
        public alertDatabaseEntities()
            : base("name=alertDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klanten> Klanten { get; set; }
        public virtual DbSet<Producten> Producten { get; set; }
        public virtual DbSet<Storingen> Storingen { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Klanten2Producten> Klanten2Producten { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
    }
}
