//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC_alert_tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storingen
    {
        public int Id { get; set; }
        public int ProductID { get; set; }
        public string Titel { get; set; }
        public string Inhoud { get; set; }
        public int EigenaarID { get; set; }
        public System.DateTime Begindatum { get; set; }
        public Nullable<System.TimeSpan> Begintijd { get; set; }
        public Nullable<System.DateTime> Einddatum { get; set; }
        public Nullable<System.TimeSpan> Eindtijd { get; set; }
        public bool IsGesloten { get; set; }
    
        public virtual Producten Producten { get; set; }
    }
}
